Add support handling deeplink
EnsembleUI/ensemble pull request #1307
Opened 2024-03-11 13:51 UTC by vinothvino42

2024-03-11 16:31 UTC, vusters requested changes

2024-03-11 16:31 UTC, vusters commented on lib/action/deep_link_action.dart
> +        return ScreenController().executeAction(context, onLinkReceived!,
null check

2024-03-11 16:31 UTC, vusters commented on lib/action/deep_link_action.dart
> +      return ScreenController().executeAction(context, onError!,
null check

2024-03-12 13:33 UTC, vinothvino42 commented on lib/action/deep_link_action.dart
> +        return ScreenController().executeAction(context, onLinkReceived!,
Fixed

2024-03-12 13:33 UTC, vinothvino42 commented on lib/action/deep_link_action.dart
> +      return ScreenController().executeAction(context, onError!,
Fixed

2024-03-13 15:57 UTC, vusters approved these changes

2024-03-18 16:19 UTC, merged