handling notification using global script
EnsembleUI/ensemble pull request #1310
Opened 2024-03-12 13:40 UTC by snehmehta

closes: https://github.com/EnsembleUI/ensemble/issues/1289

2024-03-13 15:56 UTC, vusters requested changes

2024-03-13 15:56 UTC, vusters commented on lib/framework/notification_manager.dart
> +  Future<void> handleNotification(String message) async {
What about the existing customers with the existing format. They'll break

2024-03-18 16:20 UTC, vusters approved these changes
This looks find, but please test Tin's use case to make sure it still work.

2024-03-19 11:56 UTC, snehmehta commented
okay

2024-03-24 15:16 UTC, kmahmood74 commented
@snehmehta please merge and close if you have tested the Tin changes, we need to close PRs quickly after they have been approved

2024-03-26 11:43 UTC, merged