remote provider enhanced
EnsembleUI/ensemble pull request #1389
Opened 2024-05-02 15:59 UTC by snehmehta

## Issue that this pull request solves

Closes: https://github.com/EnsembleUI/ensemble/issues/1375

## Proposed changes

This PR brings `RemoteDefinitionProvider` to parity with `LocalDefinitionProvider`.

## EDL
N.A
## Checklist

- [x] I have performed a self-review of my own code

- [ ] I have wrote proper schema in studio [Check docs](https://github.com/ensembleUI/ensemble-web-studio?tab=readme-ov-file#generate-schema)

- [ ] I have created Ensemble Kitchen Sink Example [Over here](https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screens)

- [ ] I have made corresponding changes to the documentation [Over here](https://github.com/EnsembleUI/ensemble_docs)

- [ ] I have added tests that prove my fix is effective or that my feature works

2024-05-07 01:10 UTC, kmahmood74 commented
@vusters customer has been waiting for this. Please review

2024-05-14 15:10 UTC, vusters requested changes

2024-05-14 15:10 UTC, vusters commented on lib/provider.dart
> +            forcedLocale: forcedLocale ?? Locale(i18nProps.defaultLocale),
leave it empty if not specified. You don't want/need to fallback to default.

2024-05-14 15:10 UTC, vusters commented on lib/provider.dart
> +    final env = await _readJsonFile('appConfig.json');
This should be a YAML file too.

2024-05-15 18:21 UTC, kmahmood74 approved these changes

2024-05-15 18:22 UTC, merged