ensemble chat moved to monorepo
EnsembleUI/ensemble pull request #1466
Opened 2024-07-02 12:31 UTC by snehmehta

issue: https://github.com/EnsembleUI/ensemble/issues/1442

2024-07-12 15:40 UTC, vusters requested changes
You need to add a placeholder block to EnsembleModules also. Please see others.

2024-07-24 14:59 UTC, kmahmood74 commented
@snehmehta Vu's comment was over 2 weeks ago. It's a very small change he is requesting. can you please wrap this up. This has been open for over 3 weeks

2024-07-25 12:56 UTC, snehmehta commented
> You need to add a placeholder block to EnsembleModules also. Please see others.

Yes, that is already present. 
https://github.com/EnsembleUI/ensemble/blob/9829c926c7b7359d36dc42e27ff56b1a7c4ccf55/starter/lib/generated/ensemble_modules.dart#L140

2024-08-06 13:53 UTC, kmahmood74 approved these changes

2024-08-06 14:49 UTC, merged