refactor webview with new package to support header override
EnsembleUI/ensemble pull request #1731
Opened 2024-11-21 03:24 UTC by TheNoumanDev

replaced 'https://pub.dev/packages/webview_flutter' with 'https://pub.dev/packages/flutter_inappwebview' to support headers override.
Added following new properties:
```yaml
  WebView:
    styles:
      height: ${device.height - device.safeAreaBottom - device.safeAreaTop - 10 }
    headers:
      "X-SECRET": "057cae9af7bda467269736e222bbf241e31f1c8d"
    headerOverrideRules:
      - urlPattern: 'api.acc.kpn.com'
        matchType: CONTAINS  # CONTAINS, EXACT, REGEX
        headers:
          X-SECRET: 057cae9af7bda467269736e222bbf241e31f1c8d
        mergeExisting: true
```

Test with following android and web, things worked fine by my end, iOS still needs some testing.
- Kitchen sink Example worked fine (Android, web)
- Kpn login (the top error is coming, bcz sometimes It have options API calls which don't have header but login works as it has that error):

https://github.com/user-attachments/assets/af7aaefa-a09a-4264-a5ea-80553222e06e

- Trip App worked fine on android with cookies being passed, but on web I wasn't able to login , it was given error

https://github.com/user-attachments/assets/07cf0916-d0df-4215-a665-5d89385d9e78

2024-11-21 23:47 UTC, kmahmood74 requested changes
pretty big change, let's have a zoom call to go over it

2024-11-21 23:47 UTC, kmahmood74 commented on modules/ensemble/lib/widget/webview/webview.dart
> +      (rule['headers'] as YamlMap).forEach((key, value) {
by assuming it's a YamlMap, we make it impossible for someone to set this value in js. Please just use Map

2024-11-21 23:47 UTC, kmahmood74 commented on modules/ensemble/lib/widget/webview/web/webviewstate.dart
> +  final String viewId = 'iframeElement-${DateTime.now().millisecondsSinceEpoch}';
why make it a unique viewId, is it causing memory leaks?

2024-11-21 23:47 UTC, kmahmood74 commented on modules/ensemble/lib/widget/webview/web/webviewstate.dart
>      );
we should add a dispose method here and dispose off the htmlView and iframeElement. That should get rid of the memory leak

2024-11-21 23:47 UTC, kmahmood74 commented on modules/ensemble/lib/widget/webview/native/webviewstate.dart
> +        url: Uri.parse('https://$cookieDomain'),
we can't assume that it's always https. Please get the protocol from the url as well and don't hardcode it

2024-11-21 23:47 UTC, kmahmood74 commented on modules/ensemble/lib/widget/webview/native/webviewstate.dart
> +          url: Uri.parse('https://$cookieDomain'),
same here

2024-11-25 18:04 UTC, amin-nas commented
@TheNoumanDev different error now
```
 ✝  Ensemble/ensemble/starter   webview0x45±  flutter run
Launching lib/main.dart on iPhone 16 Pro in debug mode...
Running pod install...                                              3.4s
Running Xcode build...                                                  
Xcode build done.                                           51.2s
Failed to build iOS app
Error (Xcode): ../modules/ensemble/lib/widget/webview/webview.dart:125:64: Error: The argument type 'Uri' can't be assigned to the parameter type 'WebUri?'.


Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

2024-11-29 21:44 UTC, merged