Added ScreenshotContainer
EnsembleUI/ensemble pull request #1775
Opened 2024-12-17 16:30 UTC by mehsaandev

2025-01-04 17:15 UTC, kmahmood74 commented
@mehsaandev no reviewer?

2025-01-04 17:15 UTC, kmahmood74 commented
also which ticket does this address? add the proposed yaml to that ticket. Let's get things done properly please

2025-01-06 16:39 UTC, mehsaandev commented
@snehmehta PTAL

2025-01-07 16:02 UTC, kmahmood74 requested changes

2025-01-07 16:02 UTC, kmahmood74 commented on modules/ensemble/lib/action/take_screenshot.dart
> +      rethrow;
have you actually tested it? rethrowing the error may cause issues. TEST the error case please

2025-01-10 20:42 UTC, mehsaandev commented on modules/ensemble/lib/action/take_screenshot.dart
> +      final widget = Screenshot(
Yes it is only limited to read-only widgets, it won't work for Input widgets. I'll update this to capture Input widgets as well but not sure if the screenshot will contain the value of any Input widget.

2025-01-10 20:57 UTC, mehsaandev commented on modules/ensemble/lib/action/take_screenshot.dart
> +          scopeManager: scopeManager,
Taking screenshot from bottom sheet and using widgetId of the widget in the screen works fine
And it also works for dialog as well.

2025-01-13 14:19 UTC, mehsaandev commented on modules/ensemble/lib/action/take_screenshot.dart
> +        delay: const Duration(milliseconds: 1000),
Basically in the package it was written that optimal delay is 1s so that's why I put 1000ms. It was recommended by package

2025-01-13 14:49 UTC, kmahmood74 requested changes
1. add comments everywhere in the code wherever you are making assumptions. 
2. test the action in js by calling it as `ensemble.takeScreenshot`

once done let me know

2025-01-13 16:33 UTC, mehsaandev commented
> 1. add comments everywhere in the code wherever you are making assumptions.
> 2. test the action in js by calling it as `ensemble.takeScreenshot`
> 
> once done let me know

- Added necessary comments
- previously I was not saving the screenshot in gallery because takeScreenshot action returning imageBytes in response and we can further save it using `saveFile` action but `ensemble.takeScreenshot` can't return anything and it made sense to save the screenshot so I reused the function from saveFile action and saved the screenshot when we hit `takeScreenshot`
- Tested using `ensemble.takeScreenshot` and it's working fine
- Removed delay parameter because `captureFromLongWidget` method has default delay of 1s already
- Made a separate file for file saving function in `saveFile` action so that I can reuse them in my `takeScreenshot` action

2025-01-13 17:15 UTC, kmahmood74 approved these changes

2025-01-14 16:32 UTC, merged