Updated Share Action: added file sharing support
EnsembleUI/ensemble pull request #1777
Opened 2024-12-18 10:56 UTC by mehsaandev

2024-12-18 18:44 UTC, mehsaandev commented
@kmahmood74 can you please take a look at this?

2024-12-22 23:23 UTC, kmahmood74 commented on modules/ensemble/lib/action/misc_action.dart
> +            evaluatedFiles is List ? evaluatedFiles : [evaluatedFiles];
why would it not be a list?

2024-12-22 23:23 UTC, kmahmood74 commented on modules/ensemble/lib/action/misc_action.dart
> +          if (file is Map) {
when is it a Map vs a String? how does it work across web, android and ios?

2025-01-04 17:14 UTC, kmahmood74 commented
@mehsaandev please don't just ignore my comments. Respond and let's get this done

2025-01-06 17:53 UTC, mehsaandev commented on modules/ensemble/lib/action/misc_action.dart
> +          if (file is Map) {
Added a separate function to handle the case where the file is a URL.

2025-01-06 17:57 UTC, mehsaandev commented on modules/ensemble/lib/action/misc_action.dart
> +            evaluatedFiles is List ? evaluatedFiles : [evaluatedFiles];
That was just an edge case like if the user added one file instead of a file array.

Like if user add `filerPicker.files[0]` instead of `filerPicker.files`

2025-01-07 15:44 UTC, kmahmood74 commented
@snehmehta you know this area well, could you please review this.

2025-01-08 18:27 UTC, snehmehta requested changes

2025-01-08 18:27 UTC, snehmehta commented on modules/ensemble/lib/action/misc_action.dart
> +  String getMimeType(String? extension) {
https://github.com/EnsembleUI/ensemble/blob/959406bdff99df95a51dd924e5957a823ee1db5e/modules/ensemble/lib/util/upload_utils.dart#L60

you can lookup mimeType like this instead of manual mapping.

2025-01-14 14:00 UTC, mehsaandev commented on modules/ensemble/lib/action/misc_action.dart
> +  String getMimeType(String? extension) {
Updated to this.

2025-01-14 14:43 UTC, snehmehta approved these changes
Approach feel free to merge it once testing

2025-01-14 16:39 UTC, merged