Added country search
EnsembleUI/ensemble pull request #880
Opened 2023-10-17 17:05 UTC by fullstackctp

Added the functionality for searching countries

2023-10-17 17:34 UTC, vusters reviewed
Use this for search:
- always search for name if there's at least 1 character
- additonally, search for alpha-2 if at most 2 character, and search for alpha-3 if at most 3 character

2023-10-17 17:34 UTC, vusters commented on lib/framework/data_context.dart
> +  Map<String, Function> getters() => {'getCountries': () => allCountries};
You want to move this to method so you can use `utils.getCountries()`. Getters syntax will be `utils.getCountries` which is not what we want.

2023-10-17 17:34 UTC, vusters commented on lib/framework/data_context.dart
> +        'getCountries': (value) {
Please review the jiras requirements:
#867 - support `getCountries()` and `getCountry(<alpha-2>)`
#871 - support `findCountry(<search string>)`

2023-10-17 17:34 UTC, vusters commented on lib/framework/data_context.dart
> +  List<Map<String, dynamic>> getCountryData(String userInput) {
Please simply this logic.

2023-10-19 18:14 UTC, vusters requested changes

2023-10-19 18:14 UTC, vusters commented on lib/framework/data_context.dart
> +    List<Map<String, dynamic>> alpha2List = [];
We shouldn't have to iterate through the list if the # of characters is not 2 - it's wasteful.

Even better, let's search by alpha-2 if 2 characters, and alpha-3 if 3 characters.

2023-10-19 18:14 UTC, vusters commented on lib/framework/data_context.dart
> +  List<Map<String, dynamic>> findCountry(String userInput) {
Problems with this function:
- you are making 2 passes through the list. We should only do it once for performance reason.
- By concating the list, you essentially break the existing alphabetical sort order. 

Please use 1 pass only and keep the original JSON sort order.

2023-10-23 17:19 UTC, vusters requested changes

2023-10-23 17:19 UTC, vusters commented on lib/framework/data_context.dart
> +    if (input.length == 2) {
please search alpha-2 for 2 characters, and alpha-3 for 3 characters.

2023-10-23 17:19 UTC, vusters commented on lib/framework/data_context.dart
> +        }
The value is unique. You need to break out and return once found. There is no reason to loop through the entire list.
The return type should be `Map<String, dynamic>?`. Either you find the single result or you don't.

2023-10-24 21:25 UTC, vusters approved these changes

2023-10-27 05:18 UTC, merged

2023-10-30 18:48 UTC, kmahmood74 commented
@fullstackctp this is incomplete without a kitchen sink example and documentation. No one knows how to use it. Please provide example and documentation.