Set deep link delay only for the terminated app state
EnsembleUI/ensemble pull request #959
Opened 2023-11-07 11:52 UTC by vinothvino42

Ticket: #958

2023-11-08 02:18 UTC, vusters commented
@vinothvino42 let's do this right and remove the hacky delay. Try this:
1. Add `Ensemble().addCallbackAfterInitialization(func)`. In your deep link, call this and pass the function to navigate the screen. The function will just add the function to the list of functions it stores internally.
2. in EnsembleApp initState(), after the first frame look at Ensemble().getCallbacksAfterInitialization() and execute them in order. Make sure to clear each func out before you execute, in case some error causes the function to stay there indefinintely and hose the app.

2023-11-10 13:55 UTC, vinothvino42 commented
@vusters Can you review it again?

2023-11-13 18:05 UTC, vusters requested changes
Please read my original comments before you implement this.

2023-11-13 18:05 UTC, vusters commented on lib/ensemble_app.dart
> +        final id = callback['id'] as int?;
see my comment above, it'll simplify this code.

2023-11-13 18:05 UTC, vusters commented on lib/ensemble_app.dart
> +        callbacks.removeWhere((element) => element['id'] == id);
Please read my original comment for this task. Either you put function execution inside try/catch, or you remove the item then execute (with a try catch). This way if the function throws an exception, our app is not hosed permanently. Remmeber this is what the app will do on start-up - a bad function will mess the app, regardless if you restart the app or not.

2023-11-14 11:09 UTC, vinothvino42 commented on lib/ensemble.dart
> +    final function = {
@vusters 
I tried changing it to the list of functions, but how can I pass a method with an argument to the ```addCallbackAfterInitialization(method: )``` method?

Ex: 
```dart
Ensemble()
        .addCallbackAfterInitialization(method: navigateToScreen(URL));
```

2023-11-14 22:14 UTC, vusters approved these changes

2023-11-14 22:14 UTC, merged