Fixed possible issues due to borderWidth and borderColor parameters
EnsembleUI/ensemble pull request #994
Opened 2023-11-16 06:12 UTC by hemish11

Fixes #898

Adding support for setting individual border width and color. It supports both CSS kind off syntax and individual parameters.
CSS syntax would include like `borderWidth: "4 3"` which means to apply 4 border width to top and bottom and 3 to left and right. Similarly for `borderWidth: "4 3 2"` which means it would apply border width of 4 to top, 3 to left and right and 2 to bottom. And `borderWidth: "4 3 2 1"` implies setting borderWidth of 4 to top, 3 to right, 2 to bottom and 1 to left. Same pattern is followed for `borderColor`

Also added individual parameters like `topBorderWidth`, `bottomBorderWidth` and so on.

2023-11-17 22:10 UTC, vusters requested changes

2023-11-17 22:10 UTC, vusters commented on lib/widget/lottie/web/lottiestate.dart
> -      throw LanguageError(
you want to show this error so the AppDev knows to fix this. This is not a silent error

2023-11-17 22:10 UTC, vusters commented on lib/widget/helpers/widgets.dart
> +                            boxController.borderColor.top,
does your Editor not complain about null safety? User can set borderWidth for example but exclude borderColor, and that will still show the border with default color. Please fix this.

2023-12-22 20:21 UTC, kmahmood74 commented
ok so this has been sitting around for over a month. @hemish11 please get on top of your PRs please

2023-12-23 06:29 UTC, hemish11 commented
@kmahmood74 I already added all the changes requested in it here, waiting for it to be reviewed again

2024-02-19 18:14 UTC, vusters commented
@hemish11 you only merged from main. I don't see the changes. Please check this.

2024-05-01 15:05 UTC, hemish11 commented
Temporarily closing due to monorepo

2024-05-01 15:05 UTC, closed without merging